all : clean 
	g++ test.cpp -o test

s_t1 : clean
	g++ test_s_t1.cpp -o test

s_t2 : clean
	g++ test_s_t2.cpp -o test

st3  : clean
	g++ -g test_st3.cpp -o test -std=c++11

clean :
	rm -f *.o
	rm -f test
